name:           mockery
version:        0.3.3
license:        MIT
copyright:      (c) 2015-2016 Simon Hengel
author:         Simon Hengel <sol@typeful.net>
maintainer:     Simon Hengel <sol@typeful.net>
category:       Testing
synopsis:       Support functions for automated testing
description:    Support functions for automated testing

homepage: null

github: hspec/mockery

ghc-options: -Wall

dependencies:
  - base == 4.*
  - base-compat
  - bytestring
  - temporary
  - directory
  - filepath
  - logging-facade

library:
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - mockery
      - hspec == 2.*
