license:        MIT
copyright:      (c) 2015 Simon Hengel
author:         Simon Hengel <sol@typeful.net>
maintainer:     Simon Hengel <sol@typeful.net>
category:       Testing
synopsis:       Support functions for automated testing
description:    Support functions for automated testing


github: sol/mockery

ghc-options: -Wall

dependencies:
  - base == 4.*
  - temporary
  - directory

library:
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - mockery
      - hspec == 2.*
